platform :ios, '10.0'

target 'RxSwiftDemo' do
  
  use_frameworks!

    pod 'RxSwift', '~> 4.1.2'
    pod 'SnapKit', '~> 4.0.0'
    pod 'RxCocoa', '~> 4.1.2'
    
    pod 'StreamingKit', '~> 0.1.30'
    
    pod 'RealmSwift', '3.11.1'
    
    pod 'Alamofire'

end



